fix #214 - Removes the broken ref to animation type
whatwg/compat pull request #215
Opened 2022-10-13 07:40 UTC by karlcow

- [ ] At least two implementers are interested (and none opposed):
   * …
   * …
- [ ] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at:
   * …
- [ ] [Implementation bugs](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) are filed:
   * Chrome: …
   * Firefox: …
   * Safari: …

(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)

2022-10-13 07:43 UTC, karlcow commented
Did I remove too much?

2022-10-13 07:49 UTC, karlcow commented
```
Error running preprocessor, returned code: 2.
LINK ERROR: Multiple possible 'animation-delay' property refs.
Arbitrarily chose https://drafts.csswg.org/css-animations-1/#propdef-animation-delay
To auto-select one of the following refs, insert one of these lines into a &lt;pre class=link-defaults> block:
spec:css-animations-1; type:property; text:animation-delay
spec:scroll-animations-1; type:property; text:animation-delay
'animation-delay'
make: *** [Makefile:23: deploy] Error 22
 ✘  Did not generate, due to fatal errors
```

2022-10-13 12:54 UTC, karlcow commented
Ha maybe https://github.com/tabatkins/bikeshed/pull/2364

2022-10-13 18:20 UTC, miketaylr requested changes

2022-10-13 18:20 UTC, miketaylr commented on compatibility.bs
> +Animation type: as color
Yeah, let's change this to "by computed value" https://www.w3.org/TR/web-animations/#by-computed-value

2022-10-13 22:39 UTC, karlcow commented on compatibility.bs
> +Animation type: as color
done.

2022-10-13 22:41 UTC, karlcow commented
Note that it still fails, but that seems to be a [change in bikeshed](https://github.com/tabatkins/bikeshed/pull/2364). Not sure if we should modify all refs to make it pass or wait for a fix from bikeshed?

2022-10-14 01:09 UTC, karlcow commented
ok let's see if #216 help fix things.

2022-10-14 01:10 UTC, karlcow commented
(There should be a button to be able to rebase a PR based on the current head)

2022-10-14 01:16 UTC, karlcow commented
yoohoo all green.

2022-10-14 01:36 UTC, miketaylr approved these changes
thanks!

2022-10-14 01:37 UTC, merged