Meta: add some missing meeting minutes
whatwg/compat pull request #229
Opened 2022-12-21 21:50 UTC by miketaylr

Minutes for August, October, November, and December meetings. No meeting happened in September, but I don't remember why.

2022-12-22 02:54 UTC, myakura commented
> No meeting happened in September, but I don't remember why.

TPAC, perhaps?

2022-12-22 13:30 UTC, miketaylr commented
> > No meeting happened in September, but I don't remember why.
> 
> TPAC, perhaps?

Aha! That is probably it. :)

2022-12-23 02:20 UTC, karlcow requested changes
Date to change for December,
And the index needs to be updated too for listing the recent minutes.

2022-12-23 02:20 UTC, karlcow commented on uastring/minutes/2022-12-16-minutes.md
> +# [Minutes] UA String Reduction - 2022-11-18
Probably change the date
```suggestion
# [Minutes] UA String Reduction - 2022-12-16
```

2022-12-30 01:32 UTC, karlcow approved these changes
Thanks. Still the index missing, but we can probably add it later. 🍾

2022-12-30 01:32 UTC, merged

2022-12-31 18:37 UTC, miketaylr commented
> Thanks. Still the index missing, but we can probably add it later. 🍾

whoops - just a bit slow on vacation.