Define -webkit-text-stroke sub-properties
whatwg/compat pull request #232
Opened 2023-02-07 11:16 UTC by cdoublev

*The <shorthand-name> property is a shorthand for ...* is a canonical sentence often used in CSS specs, which is followed by the names of its sub-properties, therefore the current text is ambiguous because it links to the SVG 2 spec and suggests that this spec defines its sub-properties.

- [ ] At least two implementers are interested (and none opposed):
   * …
   * …
- [ ] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at:
   * …
- [ ] [Implementation bugs](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) are filed:
   * Chromium: …
   * Gecko: …
   * WebKit: …
- [ ] [MDN issue](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) is filed: …

(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)

2023-02-09 00:18 UTC, karlcow approved these changes
Thanks @cdoublev

2023-02-09 00:20 UTC, karlcow commented
hmm why the build is failing.

2023-02-09 00:25 UTC, karlcow requested changes
@cdoublev 

> shorthand property 

could you remove the trailing whitespace after property?

2023-02-09 05:43 UTC, cdoublev commented
Fixed but I suspect that `curl` is now failing to request resources.whatwg.org in the deploy script.

2023-02-09 07:23 UTC, karlcow commented
🤯 what?!  fun time.

```
Error running preprocessor, returned code: 2.
LINK ERROR: Multiple possible 'stroke' dfn refs.
Arbitrarily chose https://svgwg.org/specs/strokes/#StrokeProperty
To auto-select one of the following refs, insert one of these lines into a &lt;pre class=link-defaults> block:
spec:svg-strokes; type:dfn; text:stroke
spec:svg2; type:dfn; text:stroke
[=stroke=]
make: *** [Makefile:23: deploy] Error 22
 ✘  Did not generate, due to fatal errors
```

2023-02-09 07:38 UTC, karlcow commented
@miketaylr @annevk do you know what is happening with bikeshed here?

2023-02-09 09:04 UTC, annevk commented
There's two definitions of stoke and you need to pick one. Presumably you would also get this error on main. What that means is that since you last ran CI the set of definitions Reffy picks up on has changed.

You might also want to file an issue against SVG telling them they shouldn't do stuff like this.

2023-02-09 09:09 UTC, cdoublev commented
I do not think link errors are fatal. It even fails only with the metadata headers using https://api.csswg.org/bikeshed/.

2023-02-09 09:10 UTC, annevk commented
We intentionally configured WHATWG CI to make all warnings and errors fatal.

2023-02-27 01:18 UTC, miketaylr commented
@cdoublev you'll want to do something like so:

```diff
diff --git a/compatibility.bs b/compatibility.bs
index 6911c2b..950796f 100644
--- a/compatibility.bs
+++ b/compatibility.bs
@@ -62,6 +62,7 @@
 spec:filter-effects-1; type:property; text:filter
 spec:infra; type:dfn; text:user agent
 spec:svg2; type:dfn; text:fill
+spec:svg2; type:dfn; text:stroke
 </pre>
 
 <!-- Commented out until we know what the heck to put here:
```
(or you can select "Allow edits from maintainers." and I can push it).

2023-02-27 09:02 UTC, cdoublev commented
Do you think the error now comes from the link on [`invalid`](https://compat.spec.whatwg.org/#the-webkit-text-stroke-width)?

`Allow edits by maintainers` is already checked, but feel free to reproduce my edit in a separate PR.

2023-02-27 15:44 UTC, miketaylr commented
> `Allow edits by maintainers` is already checked, but feel free to reproduce my edit in a separate PR.

Ah cool, I was on an airplane last night when I wrote that, and every other request was failing - could have just been that.

2023-02-27 15:47 UTC, miketaylr commented
> Do you think the error now comes from the link on [`invalid`](https://compat.spec.whatwg.org/#the-webkit-text-stroke-width)?

Yep, sigh... https://github.com/w3c/rdf-semantics/commit/af9fc781b223d8742d4d916c0f53fc06b728ef15

Can you add `spec:css-syntax-3; type:dfn; text:invalid` as well?

2023-02-27 17:24 UTC, miketaylr approved these changes
Thanks! Sorry for the delay in getting this landed.

2023-02-27 17:24 UTC, merged